# Minesweeper MVP - Docker Compose Configuration
# Author: Kyros Koh

services:
  # Main application service
  minesweeper-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minesweeper-mvp
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      # Mount data directory for persistent storage
      - minesweeper_data:/app/data
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - minesweeper-network
    labels:
      - "app=minesweeper-mvp"
      - "version=1.0.0"
      - "author=kyros-koh"

  # Optional: SQLite database service for future use
  # Uncomment when implementing the leaderboard system
  # minesweeper-db:
  #   image: alpine:latest
  #   container_name: minesweeper-db
  #   command: tail -f /dev/null
  #   volumes:
  #     - minesweeper_db:/data
  #   networks:
  #     - minesweeper-network

volumes:
  # Persistent data storage
  minesweeper_data:
    driver: local
    labels:
      - "app=minesweeper-mvp"
      - "type=data"
  
  # Optional database volume for future use
  # minesweeper_db:
  #   driver: local
  #   labels:
  #     - "app=minesweeper-mvp" 
  #     - "type=database"

networks:
  minesweeper-network:
    driver: bridge
    labels:
      - "app=minesweeper-mvp"